# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171213_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focus',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DR', 'Dancer'), ('VR', 'Videographer'), ('MN', 'Musician')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
    ]
