# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171213_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focus',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DR', 'Dancer'), ('MN', 'Musician'), ('VR', 'Videographer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
