# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171213_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focus',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MN', 'Musician'), ('DR', 'Dancer'), ('VR', 'Videographer')], max_length=30, null=True),
        ),
    ]
